/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.20
 * Generated at: 2026-03-05 13:07:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.studentportal.model.Student;
import com.studentportal.model.Batch;
import java.util.List;

public final class batchWiseStudents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.studentportal.model.Batch");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.studentportal.model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

if (session == null ||! "ADMIN".equals( session.getAttribute("ROLE"))) {
    response.sendRedirect(request.getContextPath() + "/WEB-INF/views/login.jsp");
    return;
}
    
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let typingTimer;\r\n");
      out.write("const delay=500;\r\n");
      out.write("function  searchStudents(page) {\r\n");
      out.write("	let keyword=document.getElementById(\"keyword\").value;\r\n");
      out.write("	let batchid=document.getElementById(\"batchid\").value;\r\n");
      out.write("	fetch(\"");
      out.print(request.getContextPath() );
      out.write("/admin/BatchWiseStudentsServlet?id=\"+batchid+\r\n");
      out.write("		\"&page=\"+page+\r\n");
      out.write("		\"&keyword=\"+encodeURIComponent(keyword),\r\n");
      out.write("		{\r\n");
      out.write("		headers:{\"X-Requested-With\":\"XMLHttpRequest\"}\r\n");
      out.write("	})\r\n");
      out.write("		.then(res=>res.text())\r\n");
      out.write("		.then(data=>{\r\n");
      out.write("			document.getElementById(\"result\").innerHTML=data;\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\",function(){\r\n");
      out.write("	\r\n");
      out.write("	const input=document.getElementById(\"keyword\");\r\n");
      out.write("	input.addEventListener(\"keyup\",function(){\r\n");
      out.write("		\r\n");
      out.write("		clearTimeout(typingTimer);\r\n");
      out.write("		typingTimer=setTimeout(()=>{\r\n");
      out.write("			searchStudents(1);\r\n");
      out.write("		},delay);\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("function loadPage(page){\r\n");
      out.write("	searchStudents(page);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

Integer cp=((Integer)request.getAttribute("PAGE"));
Integer tp=((Integer)request.getAttribute("TOTPAGE"));
int currentPage=cp==null?1:cp.intValue();
int totalpages=tp==null?1:tp.intValue();

      out.write('\r');
      out.write('\n');


Batch ba=(Batch)(request.getAttribute("BATCH"));
//System.out.println("ba = "+ba);


      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");

List<Student> li=(List<Student>)request.getAttribute("STUDENTS");
//System.out.println("li = "+li);

      out.write("\r\n");
      out.write("\r\n");

if(li==null||li.isEmpty()||ba==null){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<p>No Record found</p>\r\n");

}else{
	String timings=ba.getTiming();

      out.write("\r\n");
      out.write("<h1>Batch timings (");
      out.print(timings );
      out.write(")</h1>\r\n");
      out.write("<h2>Trainer name ");
      out.print(ba.getTrainer() );
      out.write("</h2>\r\n");
      out.write(" \r\n");
      out.write(" <input type=\"hidden\" id=\"batchid\" value=\"");
      out.print(ba.getId() );
      out.write("\">\r\n");
      out.write(" <input type=\"search\" id=\"keyword\" placeholder=\"Search by name / email / phone\">\r\n");
      out.write(" <div id=\"result\">\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/batchWiseStudentsTable.jsp", out, false);
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write(" <!-- <button type=\"button\" onclick=\"searchStudents(1)\">Search </button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <table border=\"1\" cellpadding=\"8\" cellspacing=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <th>Name</th>\r\n");
      out.write("  <th>Email</th>\r\n");
      out.write("  <th>Phone</th>\r\n");
      out.write("  <th>Gender</th>\r\n");
      out.write("  <th>Course</th>\r\n");
      out.write("  <th>Batch Timing</th>\r\n");
      out.write("  <th>Join Date</th>\r\n");
      out.write("  <th>Address</th>\r\n");
      out.write("  <!-- <th>Actions</th> -->\r\n");
      out.write("</tr>\r\n");

for(Student st : li){

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("  <td>");
      out.print(st.getName());
      out.write("</td>\r\n");
      out.write("  <td>");
      out.print(st.getEmail());
      out.write("</td>\r\n");
      out.write("  <td>");
      out.print(st.getPhone());
      out.write("</td>\r\n");
      out.write("  <td>");
      out.print(st.getGender());
      out.write("</td>\r\n");
      out.write("  <td>");
      out.print(st.getCourse());
      out.write("</td>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("       <td>");
      out.print(ba.getTiming());
      out.write("</td>      \r\n");
      out.write("   \r\n");
      out.write("  <td>");
      out.print(st.getJoinDate());
      out.write("</td>\r\n");
      out.write("  <td>");
      out.print(st.getAddress());
      out.write("</td>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("</tr>\r\n");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write(" \r\n");

if(currentPage>1){

      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/BatchWiseStudentsServlet\">\r\n");
      out.write(" <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage-1);
      out.write("\"/>&nbsp\r\n");
      out.write(" <input type=\"hidden\" name=\"id\" value=\"");
      out.print( ba.getId());
      out.write("\"/>&nbsp\r\n");
      out.write(" <input type=\"hidden\" name=\"keyword\" value=\"");
      out.print( request.getAttribute("KEYWORD"));
      out.write("\"/>&nbsp\r\n");
      out.write("  <input type=\"submit\" value=\"previous\"/>&nbsp\r\n");
      out.write("</form>\r\n");
 
}

      out.write('\r');
      out.write('\n');

for(int i=1;i<=totalpages;i++){
	
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/BatchWiseStudentsServlet\">\r\n");
      out.write("<input type=\"hidden\" name=\"page\" value=\"");
      out.print( i);
      out.write("\"/> &nbsp\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"");
      out.print( ba.getId());
      out.write("\"/>&nbsp\r\n");
      out.write("<input type=\"hidden\" name=\"keyword\" value=\"");
      out.print( request.getAttribute("KEYWORD") );
      out.write("\"  />&nbsp\r\n");
      out.write("<input type=\"submit\" value=\"");
      out.print( i);
      out.write("\"/> &nbsp\r\n");
      out.write("</form>	\r\n");
      out.write(" \r\n");
 
}

      out.write("\r\n");
      out.write("\r\n");

if(currentPage<totalpages){

      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/BatchWiseStudentsServlet\">\r\n");
      out.write(" <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage+1);
      out.write("\"/> &nbsp\r\n");
      out.write(" <input type=\"hidden\" name=\"id\" value=\"");
      out.print( ba.getId());
      out.write("\"/>&nbsp\r\n");
      out.write(" <input type=\"hidden\" name=\"keyword\" value=\"");
      out.print( request.getAttribute("KEYWORD") );
      out.write("\"  />&nbsp\r\n");
      out.write("  <input type=\"submit\" value=\"next\"/> &nbsp\r\n");
      out.write("</form>\r\n");
 
}

      out.write("\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
