/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.20
 * Generated at: 2026-03-05 12:56:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.studentportal.model.Batch;

public final class listBatch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.studentportal.model.Batch");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("     ");

if (session == null || ! "ADMIN".equals(session.getAttribute("ROLE"))) {
    response.sendRedirect(request.getContextPath() + "/WEB-INF/views/login.jsp");
    return;
}
    
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

List<Batch> li=(List<Batch>)request.getAttribute("BATCHES");
if(li==null||li.isEmpty()){

      out.write("\r\n");
      out.write("<h1> no records fount</h1>\r\n");

}else{
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td>BatchName</td>\r\n");
      out.write("<td>Batch Timings</td>\r\n");
      out.write("<td>Trainer</td>\r\n");
      out.write("</tr>\r\n");

for(Batch bref:li){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td>");
      out.print(bref.getName() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(bref.getTiming() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(bref.getTrainer() );
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/BatchWiseStudentsServlet\" >\r\n");
      out.write(" <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bref.getId() );
      out.write("\"/>\r\n");
      out.write("<input type=\"submit\" value=\"ViewStudents\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/EditBatchServlet\" method=\"post\">\r\n");
      out.write(" <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bref.getId() );
      out.write("\"/>\r\n");
      out.write("<input type=\"submit\" value=\"EDIT\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/DeleteBatchServlet\" method=\"post\">\r\n");
      out.write(" <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bref.getId() );
      out.write("\"/>\r\n");
      out.write("<input type=\"submit\" value=\"DELETE\"/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");

int currentPage=((Integer)request.getAttribute("PAGE")).intValue();
int totalpages=((Integer)request.getAttribute("TOTAL")).intValue();




      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");

if(currentPage>1){

      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/ListBatchServlet\">\r\n");
      out.write(" <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage-1);
      out.write("\"/>&nbsp\r\n");
      out.write("  <input type=\"submit\" value=\"previous\"/>&nbsp\r\n");
      out.write("</form>\r\n");
 
}

      out.write('\r');
      out.write('\n');

for(int i=1;i<=totalpages;i++){
	
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/ListBatchServlet\">\r\n");
      out.write("<input type=\"hidden\" name=\"page\" value=\"");
      out.print( i);
      out.write("\"/> &nbsp\r\n");
      out.write("<input type=\"submit\" value=\"");
      out.print( i);
      out.write("\"/> &nbsp\r\n");
      out.write("</form>	\r\n");
      out.write(" \r\n");
 
}

      out.write("\r\n");
      out.write("\r\n");

if(currentPage<totalpages){

      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/ListBatchServlet\">\r\n");
      out.write(" <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage+1);
      out.write("\"/> &nbsp\r\n");
      out.write("  <input type=\"submit\" value=\"next\"/> &nbsp\r\n");
      out.write("</form>\r\n");
 
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
